parameters:
  - name: imageName
    type: string
    default: 'devops-microservice'
  - name: semanticVersion
    type: string
    default: 'none'
  - name: sonarProjectName
  - name: sonarOrganization

stages:
  - stage: CI
    displayName: 'CI - Continuous Integration'
    condition: eq('${{ parameters.semanticVersion }}', 'none')
    jobs:
      - template: ../jobs/build.yml
        parameters:
          imageName: ${{ parameters.imageName }}

      - template: ../jobs/test.yml
        parameters:
          sonarProjectName: ${{ parameters.sonarProjectName }}
          sonarOrganization: ${{ parameters.sonarOrganization }}

      - template: ../jobs/docker.yml
        parameters:
          imageName: ${{ parameters.imageName }}
