parameters:
  - name: dockerfilePath
    type: string
    default: 'api_python/Dockerfile'
  - name: context
    type: string
    default: 'api_python'
  - name: imageName
    type: string
    default: 'devops-microservice'

steps:
  - script: |
      imageFullName=$(containerRegistry)/${{ parameters.imageName }}
      echo "Building: ${imageFullName}:$(configVersion)"
      docker build -t ${imageFullName}:$(configVersion) \
        -f ${{ parameters.dockerfilePath }} \
        ${{ parameters.context }}
    displayName: 'Build imagen Docker'

  - script: |
      mkdir -p $(Build.ArtifactStagingDirectory)/docker
      docker save $(containerRegistry)/${{ parameters.imageName }}:$(configVersion)| gzip > $(Build.ArtifactStagingDirectory)/docker/${{ parameters.imageName }}-$(configVersion).tar.gz
      echo "Docker image exported"
      ls -lh $(Build.ArtifactStagingDirectory)/docker/
    displayName: 'Exportar imagen Docker a tar.gz'
