parameters:
  - name: dockerfilePath
    type: string
    default: 'api_python/Dockerfile'
  - name: context
    type: string
    default: 'api_python'
  - name: imageName
    type: string
    default: 'devops-microservice'

steps:
  - script: |
      imageFullName=$(containerRegistry)/${{ parameters.imageName }}
      tagImage=$(configVersion)
      echo "Building: ${imageFullName}:${tagImage}"
      docker build -t ${imageFullName}:${tagImage} \
        -f ${{ parameters.dockerfilePath }} \
        ${{ parameters.context }}
    displayName: 'Build imagen Docker'

  - script: |
      mkdir -p $(Build.ArtifactStagingDirectory)/docker
      docker save ${imageFullName}:${tagImage} | gzip > $(Build.ArtifactStagingDirectory)/docker/${{ parameters.imageName }}-$(configVersion).tar.gz
    displayName: 'Exportar imagen Docker a tar.gz'
