parameters:
  - name: dockerfilePath
    type: string
    default: 'api_python/Dockerfile'
  - name: context
    type: string
    default: 'api_python'
  - name: imageName
    type: string
    default: 'devops-microservice'

steps:
  - script: |
      set -euo pipefail
      imageFullName=$(containerRegistry)/${{ parameters.imageName }}
      tagImage=$(configVersion)
      safeFileName=$(echo "${{ parameters.imageName }}" | tr '/' '-')
      echo "Building: ${imageFullName}:${tagImage}"
      docker build -t ${imageFullName}:${tagImage} \
        -f ${{ parameters.dockerfilePath }} \
        ${{ parameters.context }}
    displayName: 'Build imagen Docker'

  - script: |
      set -euo pipefail
      docker images
    displayName: 'Listar imágenes Docker'

  - script: |
      set -euo pipefail
      imageFullName=$(containerRegistry)/${{ parameters.imageName }}
      tagImage=$(configVersion)
      safeFileName=$(echo "${{ parameters.imageName }}" | tr '/' '-')
      mkdir -p $(Build.ArtifactStagingDirectory)/docker
      docker save ${imageFullName}:${tagImage} | gzip > "$(Build.ArtifactStagingDirectory)/docker/${safeFileName}-${tagImage}.tar.gz"
      echo "Docker image exported: ${safeFileName}-${tagImage}.tar.gz"
      ls -lh $(Build.ArtifactStagingDirectory)/docker/
    displayName: 'Exportar imagen Docker a tar.gz'
