parameters:
  - name: workingDirectory
    type: string
    default: 'api_python'

steps:
  - task: UsePythonVersion@0
    displayName: 'Configurar Python 3.11'
    inputs:
      versionSpec: '3.11'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install pytest pytest-cov flake8
    displayName: 'Instalar dependencias'
    workingDirectory: ${{ parameters.workingDirectory }}
