parameters:
  - name: imageName
    type: string
    default: 'devops-microservice'

steps:
  - task: Docker@2
    displayName: 'Login en DockerHub'
    inputs:
      command: login
      containerRegistry: $(dockerHubServiceConnection)

  - script: |
      docker tag ${{ parameters.imageName }}:$(configVersion) $(dockerHubRepository):latest
      docker tag ${{ parameters.imageName }}:$(configVersion) $(dockerHubRepository):$(configVersion)
      docker push $(dockerHubRepository):latest
      docker push $(dockerHubRepository):$(configVersion)
    displayName: 'Push imagen a DockerHub (latest + $(configVersion))'

  - task: Docker@2
    displayName: 'Logout de DockerHub'
    inputs:
      command: logout
      containerRegistry: $(dockerHubServiceConnection)
