parameters:
  - name: imageName
    type: string
    default: 'devops-microservice'

steps:
  - task: Docker@2
    displayName: 'Login en DockerHub'
    inputs:
      command: login
      containerRegistry: $(dockerHubServiceConnection)
  - script: |
      set -euo pipefail
      imageFullName=$(containerRegistry)/${{ parameters.imageName }}
      tagImage=$(configVersion)
      docker tag ${imageFullName}:${tagImage} ${imageFullName}:latest
      docker push ${imageFullName}:latest
      docker push ${imageFullName}:${tagImage}
      imageFullNameTag="${imageFullName}:${tagImage}"
      echo "##vso[task.setvariable variable=imageFullNameTag;isOutput=true]${imageFullNameTag}"
      echo "Output: ${imageFullNameTag}"
    displayName: 'Push imagen a DockerHub (latest + $(configVersion))'
    name: PushDockerHub

  - script: |
      echo "=== Docker Logout & Cleanup ==="
      docker logout $(containerRegistry) || true
      docker image prune -f || true
      echo "✅ Limpieza completada"
    displayName: 'Docker Cleanup'
    condition: always()
