parameters:
  - name: imageName
    type: string
    default: 'devops-microservice'

steps:
  - task: Docker@2
    displayName: 'Login en DockerHub'
    inputs:
      command: login
      containerRegistry: $(dockerHubServiceConnection)
  - script: |
      set -euo pipefail
      imageFullName=$(containerRegistry)/${{ parameters.imageName }}
      tagImage=$(configVersion)
      docker tag ${imageFullName}:${tagImage} ${imageFullName}:latest
      docker push ${imageFullName}:latest
      docker push ${imageFullName}:${tagImage}
      echo "##vso[task.setvariable variable=imageFullName;isOutput=true]${imageFullName}"
      echo "##vso[task.setvariable variable=tagImage;isOutput=true]${tagImage}"
      echo "Output: ${imageFullName}:${tagImage}"
    displayName: 'Push imagen a DockerHub (latest + $(configVersion))'
    name: PushDockerHub

  - task: Docker@2
    displayName: 'Logout de DockerHub'
    inputs:
      command: logout
      containerRegistry: $(dockerHubServiceConnection)
