parameters:
- name: sonarProjectName
- name: sonarOrganization
steps:
  - task: SonarCloudPrepare@3
    displayName: 'Preparar análisis SonarCloud'
    inputs:
      SonarCloud: $(sonarServiceConnection)
      organization: ${{ parameters.sonarOrganization }}
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: ${{ parameters.sonarOrganization }}_${{ parameters.sonarProjectName }}
      cliProjectName: ${{ parameters.sonarProjectName }}
      cliSources: 'api_python'
      extraProperties: |
        sonar.python.coverage.reportPaths=$(Common.TestResultsDirectory)/coverage.xml
        sonar.python.xunit.reportPath=$(Common.TestResultsDirectory)/test-results.xml
        sonar.exclusions=**/tests/**,**/__pycache__/**

  - task: SonarCloudAnalyze@3
    displayName: 'Ejecutar análisis SonarCloud'

  - task: SonarCloudPublish@3
    displayName: 'Publicar resultados SonarCloud'
    inputs:
      pollingTimeoutSec: '300'
