apiVersion: v1
kind: Secret
metadata:
  name: devops-microservice-secret
  namespace: devops-microservice
  labels:
    app: devops-microservice
type: Opaque
stringData:
  SECRET_KEY: "your-secret-key-change-this-in-production"
  API_KEY: "2f5ae96c-b558-4c7b-a590-a501ae1c3f6c"
