parameters:
  - name: sonarProjectName
  - name: sonarOrganization

jobs:
  - job: TestJob
    displayName: 'Unit Tests & Sonar Analysis'
    dependsOn: BuildJob
    variables:
      configVersion: $[ dependencies.BuildJob.outputs['readVersion.configVersion'] ]
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      - task: DownloadBuildArtifacts@1
        displayName: 'Download Build Artifacts'
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'build-artifacts'
          downloadPath: '$(Pipeline.Workspace)'

      - template: ../steps/python/install-dependencies.yml
        parameters:
          workingDirectory: 'api_python'

      - template: ../steps/test/run-unit-tests.yml
        parameters:
          workingDirectory: 'api_python'

      - template: ../steps/test/sonar-analysis.yml
        parameters:
          sonarProjectName: ${{ parameters.sonarProjectName }}
          sonarOrganization: ${{ parameters.sonarOrganization }}
