parameters:
  - name: dockerfilePath
    type: string
    default: 'api_python/Dockerfile'
  - name: context
    type: string
    default: 'api_python'
  - name: imageName
    type: string
    default: 'devops-microservice'

steps:
  - script: |
      set -euo pipefail
      imageFullName=$(containerRegistry)/${{ parameters.imageName }}
      tagImage=$(configVersion)
      safeFileName=$(echo "${{ parameters.imageName }}" | tr '/' '-')
      echo "Building: ${imageFullName}:${tagImage}"
      docker build -t ${imageFullName}:${tagImage} \
        -f ${{ parameters.dockerfilePath }} \
        ${{ parameters.context }}
    displayName: 'Docker Build'

  - script: |
      set -euo pipefail
      docker images
    displayName: 'List Docker Images'
